version: '3.8'

services:
  golang_app:
    image: mattgomes28/urchin-golang:0.3
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: .
        target: /urchin
        volume:
          nocopy: true
    command: ./urchin/compose-run.sh
    depends_on:
      mariadb:
        condition: service_healthy
    restart: always
    networks:
      - common-net

  mariadb:
    image: mariadb:11.2.3-jammy
    container_name: mariadb
    environment:
      MARIADB_PASSWORD: root
      MARIADB_DATABASE: urchin
      MARIADB_ROOT_PASSWORD: root
    healthcheck:
      test: [ "CMD", "mariadb", "-u", "root", "-proot", "-e", "USE urchin" ]
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      - common-net

networks:
  common-net: {}
