# Address to the MariaDB database
database_address = "localhost"

# User to access datbaase
database_user = "root"

# Password for the database user
database_password = "root"

# port
database_port = 3306

# name of database where urchin's
# migrations was installed
database_name = "gocms"

# port to run the webserver on
webserver_port = 8080

# port to run the admin app on
admin_port = 8081

# Directory to use for storing uploaded images.
image_dir = "./images"

# Enable/disable endpoint cache
cache_enabled = true

# Recaptcha settings
recaptcha_sitekey = "6LecCewpAAAAAK7QS2SwuyCIDzwlyXMs4J1Z5LBq"
recaptcha_secret = "6LecCewpAAAAAPP8Aaxh6jWaDE1xG_MBQa1OOs8f"


[navbar]
links = [
    { name = "Home", href = "/", title = "Homepage" },
    { name = "About", href = "/about", title = "About page" },
    { name = "Services", href = "/services", title = "Services page" },
    { name = "Images", href = "/images", title = "Images page" },
    { name = "Products", href = "/products", title = "Product cards page"},
    { name = "Contact", href = "/contact", title = "Contacts page" },
]
