services:
  urchin_admin_app:
    container_name: urchin_admin_app
    image: mattgomes28/urchin-golang:0.7
    ports:
      - "8081:8081"
    volumes:
      - type: bind
        source: ${GITHUB_WORKSPACE:-..}
        target: /urchin
        bind:
          create_host_path: true
    command: /urchin/docker/start-admin-app.sh
    healthcheck:
      test: [ "CMD", "sh", "-c", "wget --no-verbose --tries=1 --spider http://localhost:8081/health || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 10
    depends_on:
      mariadb:
        condition: service_healthy
    restart: always
    networks:
      - common-net

  urchin_app:
    container_name: urchin_app
    image: mattgomes28/urchin-golang:0.7
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ${GITHUB_WORKSPACE:-..}
        target: /urchin
        bind:
          create_host_path: true
    command: /urchin/docker/start-app.sh
    healthcheck:
      test: [ "CMD", "sh", "-c", "wget --no-verbose --tries=1 --spider http://localhost:8080/health || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 10
    depends_on:
      urchin_admin_app:
        condition: service_healthy
      mariadb:
        condition: service_healthy
    restart: always
    networks:
      - common-net


  mariadb:
    image: mariadb:11.2.3-jammy
    container_name: mariadb
    ports:
      - "3336:3306"
    env_file:
      - ../.dev.env
    healthcheck:
      test: [ "CMD", "mariadb", "-u", "root", "-proot", "-e", "USE urchin" ]
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      - common-net

networks:
  common-net: {}
