services:
  urchin_app:
    image: mattgomes28/urchin-golang:0.4
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ..
        target: /urchin
        volume:
          nocopy: true
    command: /urchin/docker/start-app.sh
    depends_on:
      mariadb:
        condition: service_healthy
    restart: always
    networks:
      - common-net

  urchin_admin_app:
    image: mattgomes28/urchin-golang:0.4
    ports:
      - "8081:8081"
    volumes:
      - type: bind
        source: ..
        target: /urchin
        volume:
          nocopy: true
    command: /urchin/docker/start-admin-app.sh
    depends_on:
      mariadb:
        condition: service_healthy
    restart: always
    networks:
      - common-net

  mariadb:
    image: mariadb:11.2.3-jammy
    container_name: mariadb
    env_file:
      - ../.dev.env
    healthcheck:
      test: [ "CMD", "mariadb", "-u", "root", "-proot", "-e", "USE urchin" ]
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      - common-net

networks:
  common-net: {}
