# Address to the MariaDB database
database_address = "mariadb"

# User to access datbaase
database_user = "urchin"

# Password for the database user
database_password = "urchinpw"

# port
database_port = 3306

# name of database where urchin's
# migrations was installed
database_name = "urchin"

# port to run the webserver on
webserver_port = 8080

# Directory to use for storing uploaded images.
image_dir = "./images"

[navbar]
links = [
    { name = "Home", href = "/", title = "Homepage" },
    { name = "About", href = "/about", title = "About page" },
    { name = "Services", href = "/services", title = "Services page" },
    { name = "Images", href = "/images", title = "Images page" },
    { name = "Contact", href = "/contact", title = "Contacts page" },
]
